# Generated by Django 4.2.8 on 2023-12-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapi', '0003_rename_type_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_url',
        ),
    ]
