# Generated by Django 4.2.8 on 2023-12-07 16:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapi', '0004_rename_image_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='neighbor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 7))]),
        ),
    ]
